# Generated by Django 5.2 on 2025-11-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
